//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

	public struct TemplateGridEnum
	{
		public TileShape shape; //put an enum in a header to include... via using?
		public int size;
		//public ArrayList<TileType> Array;
};


public enum TileShape{
	Circle,
	Cone,
	Line,
	SingleTile
};